spring:
  application:
    name: iot-808-devonl-service
  data:
    mongodb:
      host: 19.87.22.3
      port: 27017
      database: p808
  cloud:
    consul:
      host: 19.87.22.12
      port: 8500
      discovery:
        register: true
        hostname: 19.87.22.12
        serviceName: ${spring.application.name}
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        tags: urlprefix-/${spring.application.name}
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
server:
  port: 8728